// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: servidor.proto

package servidoresb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servidor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_servidor_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Vacio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_servidor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_servidor_proto_rawDescGZIP(), []int{1}
}

type ClienteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Producto []*ProducoRequest `protobuf:"bytes,1,rep,name=producto,proto3" json:"producto,omitempty"`
}

func (x *ClienteRequest) Reset() {
	*x = ClienteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClienteRequest) ProtoMessage() {}

func (x *ClienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servidor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClienteRequest.ProtoReflect.Descriptor instead.
func (*ClienteRequest) Descriptor() ([]byte, []int) {
	return file_servidor_proto_rawDescGZIP(), []int{2}
}

func (x *ClienteRequest) GetProducto() []*ProducoRequest {
	if x != nil {
		return x.Producto
	}
	return nil
}

type ProducoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre   string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Cantidad int32  `protobuf:"varint,2,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
}

func (x *ProducoRequest) Reset() {
	*x = ProducoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducoRequest) ProtoMessage() {}

func (x *ProducoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servidor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducoRequest.ProtoReflect.Descriptor instead.
func (*ProducoRequest) Descriptor() ([]byte, []int) {
	return file_servidor_proto_rawDescGZIP(), []int{3}
}

func (x *ProducoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ProducoRequest) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

type GeneralResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *GeneralResponse) Reset() {
	*x = GeneralResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResponse) ProtoMessage() {}

func (x *GeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servidor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResponse.ProtoReflect.Descriptor instead.
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return file_servidor_proto_rawDescGZIP(), []int{4}
}

func (x *GeneralResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ListaPedidosReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pedidos []*PedidoReqRes `protobuf:"bytes,1,rep,name=pedidos,proto3" json:"pedidos,omitempty"`
}

func (x *ListaPedidosReponse) Reset() {
	*x = ListaPedidosReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListaPedidosReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaPedidosReponse) ProtoMessage() {}

func (x *ListaPedidosReponse) ProtoReflect() protoreflect.Message {
	mi := &file_servidor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaPedidosReponse.ProtoReflect.Descriptor instead.
func (*ListaPedidosReponse) Descriptor() ([]byte, []int) {
	return file_servidor_proto_rawDescGZIP(), []int{5}
}

func (x *ListaPedidosReponse) GetPedidos() []*PedidoReqRes {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

type PedidoReqRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto []*ProducoRequest `protobuf:"bytes,2,rep,name=producto,proto3" json:"producto,omitempty"`
}

func (x *PedidoReqRes) Reset() {
	*x = PedidoReqRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servidor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedidoReqRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoReqRes) ProtoMessage() {}

func (x *PedidoReqRes) ProtoReflect() protoreflect.Message {
	mi := &file_servidor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoReqRes.ProtoReflect.Descriptor instead.
func (*PedidoReqRes) Descriptor() ([]byte, []int) {
	return file_servidor_proto_rawDescGZIP(), []int{6}
}

func (x *PedidoReqRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PedidoReqRes) GetProducto() []*ProducoRequest {
	if x != nil {
		return x.Producto
	}
	return nil
}

var File_servidor_proto protoreflect.FileDescriptor

var file_servidor_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x22, 0x42, 0x0a, 0x0e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f,
	0x22, 0x44, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61,
	0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e,
	0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x65,
	0x64, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x52,
	0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x22, 0x50, 0x0a, 0x0c, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x32, 0xe8, 0x03, 0x0a, 0x0e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x14, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x12, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56,
	0x61, 0x63, 0x69, 0x6f, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x61, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6f, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x74, 0x12, 0x0b, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x45, 0x6e,
	0x63, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6f, 0x12, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x63, 0x69, 0x6f, 0x1a,
	0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0f, 0x54, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x45, 0x6e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x0f, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x67, 0x63, 0x65, 0x6c, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servidor_proto_rawDescOnce sync.Once
	file_servidor_proto_rawDescData = file_servidor_proto_rawDesc
)

func file_servidor_proto_rawDescGZIP() []byte {
	file_servidor_proto_rawDescOnce.Do(func() {
		file_servidor_proto_rawDescData = protoimpl.X.CompressGZIP(file_servidor_proto_rawDescData)
	})
	return file_servidor_proto_rawDescData
}

var file_servidor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_servidor_proto_goTypes = []interface{}{
	(*IdRequest)(nil),           // 0: grpc.idRequest
	(*Vacio)(nil),               // 1: grpc.Vacio
	(*ClienteRequest)(nil),      // 2: grpc.ClienteRequest
	(*ProducoRequest)(nil),      // 3: grpc.ProducoRequest
	(*GeneralResponse)(nil),     // 4: grpc.GeneralResponse
	(*ListaPedidosReponse)(nil), // 5: grpc.ListaPedidosReponse
	(*PedidoReqRes)(nil),        // 6: grpc.PedidoReqRes
}
var file_servidor_proto_depIdxs = []int32{
	3,  // 0: grpc.ClienteRequest.producto:type_name -> grpc.ProducoRequest
	6,  // 1: grpc.ListaPedidosReponse.pedidos:type_name -> grpc.PedidoReqRes
	3,  // 2: grpc.PedidoReqRes.producto:type_name -> grpc.ProducoRequest
	2,  // 3: grpc.ClienteService.CrearPedido:input_type -> grpc.ClienteRequest
	1,  // 4: grpc.ClienteService.GetPedidos:input_type -> grpc.Vacio
	0,  // 5: grpc.ClienteService.GetEstadoRestaurant:input_type -> grpc.idRequest
	0,  // 6: grpc.ClienteService.GetEstadoReparto:input_type -> grpc.idRequest
	1,  // 7: grpc.ClienteService.GetPedidosRest:input_type -> grpc.Vacio
	0,  // 8: grpc.ClienteService.EnviarEncargo:input_type -> grpc.idRequest
	1,  // 9: grpc.ClienteService.GetPedidosReparto:input_type -> grpc.Vacio
	0,  // 10: grpc.ClienteService.TerminarEncargo:input_type -> grpc.idRequest
	4,  // 11: grpc.ClienteService.CrearPedido:output_type -> grpc.GeneralResponse
	5,  // 12: grpc.ClienteService.GetPedidos:output_type -> grpc.ListaPedidosReponse
	4,  // 13: grpc.ClienteService.GetEstadoRestaurant:output_type -> grpc.GeneralResponse
	4,  // 14: grpc.ClienteService.GetEstadoReparto:output_type -> grpc.GeneralResponse
	5,  // 15: grpc.ClienteService.GetPedidosRest:output_type -> grpc.ListaPedidosReponse
	4,  // 16: grpc.ClienteService.EnviarEncargo:output_type -> grpc.GeneralResponse
	5,  // 17: grpc.ClienteService.GetPedidosReparto:output_type -> grpc.ListaPedidosReponse
	4,  // 18: grpc.ClienteService.TerminarEncargo:output_type -> grpc.GeneralResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_servidor_proto_init() }
func file_servidor_proto_init() {
	if File_servidor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_servidor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servidor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servidor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClienteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servidor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servidor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servidor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListaPedidosReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servidor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PedidoReqRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servidor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servidor_proto_goTypes,
		DependencyIndexes: file_servidor_proto_depIdxs,
		MessageInfos:      file_servidor_proto_msgTypes,
	}.Build()
	File_servidor_proto = out.File
	file_servidor_proto_rawDesc = nil
	file_servidor_proto_goTypes = nil
	file_servidor_proto_depIdxs = nil
}
